# Generated by Django 2.1 on 2018-08-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameoverstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameoverstatistics',
            name='correct_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
